apiVersion: apps/v1
kind: Deployment
metadata:
  name: hallo-welt
  namespace: website
  annotations:
    author: moerwald
spec:
  selector:
    matchLabels:
      app: hallo-welt
  template:
    metadata:
      labels:
        app: hallo-welt
      annotations:
        author: moerwald
    spec:
      containers:
      - name: hallo-welt
        image: goloroden/hello-world:latest
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hallo-welt
  namespace: website
spec:
  selector:
    app: hallo-welt
  ports:
  - name: http
    port: 80
    targetPort: http
  type: NodePort
